"""Export feed items in various formats: JSON, Markdown, digest."""
from __future__ import annotations

import json
from collections import defaultdict
from datetime import date

from .constants import CATEGORY_LABELS, CATEGORY_ORDER
from .models import Item


def _group(items: list[Item]) -> dict[str, list[Item]]:
    groups: dict[str, list[Item]] = defaultdict(list)
    seen: set[str] = set()
    for it in items:
        if not it.url or it.url in seen:
            continue
        seen.add(it.url)
        groups[it.category].append(it)
    for cat in groups:
        groups[cat].sort(key=lambda x: (x.score, x.published), reverse=True)
    return groups


def to_json(items: list[Item], summaries: dict[str, str]) -> str:
    """Export items + summaries as JSON."""
    records = []
    for it in items:
        records.append({
            "title": it.title,
            "url": it.url,
            "source": it.source,
            "category": it.category,
            "published": it.published.isoformat(),
            "score": it.score,
            "summary": summaries.get(it.url, ""),
        })
    return json.dumps(records, indent=2, ensure_ascii=False)


def to_markdown(items: list[Item], summaries: dict[str, str], days: int) -> str:
    """Export items as a Markdown document."""
    groups = _group(items)
    lines = [
        f"# AI News Digest",
        f"*Last {days} days — {len(items)} items — {date.today().isoformat()}*",
        "",
    ]
    for cat in CATEGORY_ORDER:
        cat_items = groups.get(cat, [])
        if not cat_items or cat == "subscribed":
            continue
        label = CATEGORY_LABELS.get(cat, cat)
        lines.append(f"## {label} ({len(cat_items)})")
        lines.append("")
        for it in cat_items:
            date_str = it.published.strftime("%b %d")
            score = f" ({it.score}pts)" if it.score else ""
            lines.append(f"### [{it.title}]({it.url})")
            lines.append(f"*{it.source} — {date_str}{score}*")
            summary = summaries.get(it.url, "")
            if summary:
                lines.append(f"\n{summary}")
            lines.append("")
    return "\n".join(lines)


def to_digest(items: list[Item], summaries: dict[str, str], days: int, limit: int = 5) -> str:
    """Generate a concise digest (top N per category) suitable for Slack/email.

    Uses simple formatting that renders well in Slack, email, and Markdown.
    """
    groups = _group(items)
    lines = [
        f"AI News Roundup — {date.today().strftime('%B %d, %Y')}",
        f"Top stories from the last {days} days",
        "=" * 50,
        "",
    ]
    for cat in CATEGORY_ORDER:
        cat_items = groups.get(cat, [])
        if not cat_items or cat == "subscribed":
            continue
        label = CATEGORY_LABELS.get(cat, cat)
        top = cat_items[:limit]
        lines.append(f"--- {label} ({len(cat_items)} total, showing top {len(top)}) ---")
        lines.append("")
        for it in top:
            score = f" [{it.score}pts]" if it.score else ""
            lines.append(f"  > {it.title}{score}")
            lines.append(f"    {it.url}")
            summary = summaries.get(it.url, "")
            if summary:
                lines.append(f"    {summary}")
            lines.append("")
    lines.append("—")
    lines.append("Generated by clankernewsdump")
    return "\n".join(lines)
